sudo: required

services:
  - docker

env:
  TAG=$(git describe --long --always --tags)
  PATH=/snap/bin:$PATH

before_install:
  - sudo apt-get update && sudo apt-get install --only-upgrade openssl
  - sudo pip install --user urllib3[secure] --upgrade
  - tar -czf resources.tar.gz resources/
  - docker build -t dnanexus/parliament2:$TAG .
  - docker tag dnanexus/parliament2:$TAG dnanexus/parliament2
  - sudo bash test/set_up_tests.sh

jobs:
  include:
    - script: docker run dnanexus/parliament2:$TAG -q -h
    - script: docker run -v /home/dnanexus/in:/home/dnanexus/in -v /home/dnanexus/out:/home/dnanexus/out dnanexus/parliament2:$TAG --bam /home/dnanexus/in/small_input.bam --bai /home/dnanexus/in/small_input.bai --ref_genome /home/dnanexus/in/ref.fa.gz --fai /home/dnanexus/in/ref.fa.fai --prefix breakdancer --breakdancer && ls -sh /home/dnanexus/out
    - script: sudo bash test_scripts/breakseq_test.sh
    - script: sudo bash test_scripts/cnvnator_test.sh
    - script: sudo bash test_scripts/delly_deletion_test.sh
    - script: sudo bash test_scripts/delly_duplication_test.sh
    - script: sudo bash test_scripts/delly_insertion_test.sh
    - script: sudo bash test_scripts/delly_inversion_test.sh
    - script: sudo bash test_scripts/lumpy_test.sh
    - script: sudo bash test_scripts/manta_test.sh
    - script: sudo bash test_scripts/svviz_test.sh
    - script: sudo bash test_scripts/full_small_test.sh

branches:
  except:
  - hgsc

language: python
python: 
  - "2.7.13"