sudo: required

services:
  - docker

env:
  SHORT_COMMIT=`echo $TRAVIS_COMMIT | cut -c1-7`
  CURRENT_DATE=`date '+%Y%m%d%H%M%S'`
  TAG="${CURRENT_DATE}_${SHORT_COMMIT}"
  PATH=/snap/bin:$PATH
  tar -czf resources.tar.gz resources/
  wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
  tar zxf dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
  source dx-toolkit/environment

before_install:
  - docker build -t dnanexus/parliament2:$TAG .

jobs:
  include:
    - stage: test docker build
      script: docker run dnanexus/parliament2:$TAG -h
    - stage: small tests
      script: test_scripts/small_test.sh
    - stage: dnanexus tests (hg002)
      script: echo "hello"

  # deploy dx-toolkit
# - wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
# - tar zxf dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
# - source dx-toolkit/environment
# - dx select project-Bz84jg80pyJ3F9Y0853zBjb9
# - GIT_REVISION="$(git describe --long --tags --dirty --always)"
# - folder_name="$(date +/%Y-%m/%d-%H%M%S)_${GIT_REVISION}/"
# - dx mkdir -p $folder_name
# - dx run chorus_query -iinput_vcf=project-Bz84jg80pyJ3F9Y0853zBjb9:file-BxVP9p8081jzbGJ3V9z5792k --folder=$folder_name --yes --brief --wait --watch

branches:
  except:
  - hgsc

language: python
python: 
  - "2.7"